# Generated by Django 4.1.7 on 2023-04-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whys_app_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='attributes_ids',
            field=models.ManyToManyField(to='whys_app_data.attribute'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='nazev',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='catalog',
            name='obrazek_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='whys_app_data.image'),
        ),
    ]
