# Generated by Django 4.1.7 on 2023-04-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whys_app_data', '0002_catalog_attributes_ids_catalog_nazev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='nazev',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='nazev',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
