# Generated by Django 4.1.7 on 2023-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whys_app_data', '0003_alter_image_nazev_alter_productimage_nazev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='attributes_ids',
            field=models.ManyToManyField(null=True, to='whys_app_data.attribute'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='products_ids',
            field=models.ManyToManyField(null=True, to='whys_app_data.product'),
        ),
    ]
